export const jobs = [
    {
        image: require("../assets/jobs_logos/invoke.png"),
        company: "Invoke Media",
        heading1: "WEB DEVELOPER CO-OP",
        heading2: "May 2023 - Sept 2023",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: true,
        top: '25%',
        right: '72%',
    },
    {
        image: require("../assets/jobs_logos/alianza.png"),
        company: "Alianza",
        heading1: "QA CO-OP",
        heading2: "Jan 2023 - May 2023",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: true,
        top: '55%',
        right: '40%',
    },
    {
        image: require("../assets/jobs_logos/cra.png"),
        company: "CRA",
        heading1: "STUDENT IT INFRASTRUCTURE ANALYST",
        heading2: "May 2022 - Sept 2022",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: true,
        top: '7%',
        right: '22%',
    },
    {
        image: require("../assets/jobs_logos/biztech.png"),
        company: "UBC Biztech",
        heading1: "WEB DESIGNER",
        heading2: "June 2022 - present",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: false,
        top: '35%',
        right: '40%',
    },
    {
        image: require("../assets/jobs_logos/uxhub.png"),
        company: "UBC UX Hub",
        heading1: "GRAPHIC DESIGNER",
        heading2: "Sept 2022 - present",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: false,
        top: '35%',
        right: '40%',
    },
    {
        image: require("../assets/jobs_logos/nnect.png"),
        company: "NNECT",
        heading1: "VOLUNTEER DEVELOPER",
        heading2: "Feb 2022 - May 2022",
        description: "2 sentence description using some words here some words there bla bla bla. And more words just to add and simulate what it would look like.",
        show: false,
        top: '35%',
        right: '40%',
    },

]